package transacao.Service;

import java.util.Random;

public class Senha {

	public static String autoGenerated(int number) {
		
		Random random = new Random();
		String senha;
		Integer vetor[] = new Integer[number]; 
		
		for(int i = 0; i<number; i++) {
			vetor[i] = random.nextInt(9);
		}
		
		StringBuilder sb = new StringBuilder();
		
		for(int i = 0; i<number ; i++) {
			sb.append(vetor[i]);
		}

		senha = sb.toString();
		
		return senha;
	}
}
